# Generated by Django 5.2.6 on 2025-10-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_ubicacion",
                    models.CharField(
                        choices=[
                            ("sede", "Sede (Edificio Principal)"),
                            ("oficina", "Oficina (Piso/Ala)"),
                            ("area", "Área Específica (Sala/Cuarto)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nombre_sede", models.CharField(max_length=100)),
                ("codigo_unico", models.CharField(max_length=50, unique=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "dispositivo_biometrico",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("huella", "Lector de Huella Dactilar"),
                            ("Tarjeta", "Tarjeta de Acceso"),
                            ("PIN", "PIN"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nivel_seguridad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("alto", "Alto"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["nombre_sede"],},
        ),
    ]
