# Generated by Django 5.2.6 on 2025-11-05 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_ubicacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="ubicacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleados",
                to="usuario.ubicacion",
            ),
        ),
    ]
