# Generated by Django 5.2.6 on 2025-11-08 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0003_personal_ubicacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Dispositivo"
                    ),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Serie"
                    ),
                ),
                (
                    "tipo_sede",
                    models.CharField(
                        choices=[
                            ("SEDE_PRINCIPAL", "Sede Principal"),
                            ("ALMACEN", "Almacén"),
                            ("OFICINA", "Oficina"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Sede",
                    ),
                ),
                (
                    "direccion_fisica",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dirección Física"
                    ),
                ),
                (
                    "direccion_ip",
                    models.GenericIPAddressField(verbose_name="Dirección IP"),
                ),
                (
                    "zona_horaria",
                    models.CharField(
                        choices=[
                            ("America/Argentina/Buenos_Aires", "Buenos Aires (GMT-3)"),
                            ("America/Cordoba", "Córdoba (GMT-3)"),
                            ("America/Mendoza", "Mendoza (GMT-3)"),
                        ],
                        max_length=50,
                        verbose_name="Zona Horaria",
                    ),
                ),
                (
                    "intervalo_solicitud",
                    models.IntegerField(
                        default=5, verbose_name="Intervalo de Solicitud (minutos)"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("PAUSADO", "Pausado"),
                            ("INACTIVO", "Inactivo"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                        verbose_name="Estado del Dispositivo",
                    ),
                ),
                (
                    "tipo_dispositivo",
                    models.CharField(
                        choices=[
                            ("Lector de Huella", "Lector de Huella"),
                            ("Lector de Iris", "Lector de Iris"),
                            ("Reconocimiento Facial", "Reconocimiento Facial"),
                            ("Tarjeta RFID", "Tarjeta RFID"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Dispositivo",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("ultima_conexion", models.DateTimeField(blank=True, null=True)),
                (
                    "ubicacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispositivos",
                        to="usuario.ubicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo",
                "verbose_name_plural": "Dispositivos",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
