# Generated by Django 5.2.6 on 2025-10-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0002_rename_is_created_task_is_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Edificio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
            ],
        ),
    ]
